In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r"C:\Users\KIIT\OneDrive\urban_traffic\data\raw\urban_traffic_dataset.csv")

In [4]:
data.head()

,timestamp,intersection_id,hour,minute,day_of_week,is_weekend,is_holiday,event_nearby,temperature_c,rain_mm_15min,...,avg_waiting_time_sec,queue_length_veh,incident_flag,prev_count_15min,prev_count_1h,count_same_time_yesterday,count_same_time_last_week,rolling_mean_1h,target_next_count,target_congestion
0,2025-01-06 00:00:00,INT_01_CBD,0,0,0,0,0,0,2.6,0.0,...,11.5,1.5,0,NaN,NaN,NaN,NaN,NaN,36.0,Low
1,2025-01-06 00:15:00,INT_01_CBD,0,15,0,0,0,0,2.7,0.0,...,3.4,0.3,0,23.0,NaN,NaN,NaN,NaN,28.0,Low
2,2025-01-06 00:30:00,INT_01_CBD,0,30,0,0,0,0,2.4,0.0,...,11.3,0.0,0,36.0,NaN,NaN,NaN,NaN,33.0,Low
3,2025-01-06 00:45:00,INT_01_CBD,0,45,0,0,0,0,1.5,0.0,...,5.8,0.4,0,28.0,NaN,NaN,NaN,NaN,19.0,Low
4,2025-01-06 01:00:00,INT_01_CBD,1,0,0,0,0,0,3.1,0.0,...,0.0,0.0,0,33.0,23.0,NaN,NaN,30.0,32.0,Low

In [7]:
data.shape

(69120, 24)

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 69120 entries, 0 to 69119
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   timestamp                  69120 non-null  str
 1   intersection_id            69120 non-null  str
 2   hour                       69120 non-null  int64
 3   minute                     69120 non-null  int64
 4   day_of_week                69120 non-null  int64
 5   is_weekend                 69120 non-null  int64
 6   is_holiday                 69120 non-null  int64
 7   event_nearby               69120 non-null  int64
 8   temperature_c              69120 non-null  float64
 9   rain_mm_15min              69120 non-null  float64
 10  road_capacity_veh_15min    69120 non-null  int64
 11  vehicle_count              69120 non-null  int64
 12  avg_speed_kmh              68459 non-null  float64
 13  vehicle_density_per_km     68481 non-null  float64
 14  avg_waiting_time_sec       68388 non-null  float64
 15  queue_length_veh           68415 non-null  float64
 16  incident_flag              69120 non-null  int64
 17  prev_count_15min           69116 non-null  float64
 18  prev_count_1h              69104 non-null  float64
 19  count_same_time_yesterday  68736 non-null  float64
 20  count_same_time_last_week  66432 non-null  float64
 21  rolling_mean_1h            69104 non-null  float64
 22  target_next_count          69116 non-null  float64
 23  target_congestion          69116 non-null  str
dtypes: float64(12), int64(9), str(3)
memory usage: 12.7 MB

In [9]:
data.isnull().sum()

timestamp                       0
intersection_id                 0
hour                            0
minute                          0
day_of_week                     0
is_weekend                      0
is_holiday                      0
event_nearby                    0
temperature_c                   0
rain_mm_15min                   0
road_capacity_veh_15min         0
vehicle_count                   0
avg_speed_kmh                 661
vehicle_density_per_km        639
avg_waiting_time_sec          732
queue_length_veh              705
incident_flag                   0
prev_count_15min                4
prev_count_1h                  16
count_same_time_yesterday     384
count_same_time_last_week    2688
rolling_mean_1h                16
target_next_count               4
target_congestion               4
dtype: int64

In [10]:
data = data.dropna()

In [11]:
data.isnull().sum()

timestamp                    0
intersection_id              0
hour                         0
minute                       0
day_of_week                  0
is_weekend                   0
is_holiday                   0
event_nearby                 0
temperature_c                0
rain_mm_15min                0
road_capacity_veh_15min      0
vehicle_count                0
avg_speed_kmh                0
vehicle_density_per_km       0
avg_waiting_time_sec         0
queue_length_veh             0
incident_flag                0
prev_count_15min             0
prev_count_1h                0
count_same_time_yesterday    0
count_same_time_last_week    0
rolling_mean_1h              0
target_next_count            0
target_congestion            0
dtype: int64

In [12]:
data.duplicated().sum()

np.int64(0)

In [13]:
data.describe()

,hour,minute,day_of_week,is_weekend,is_holiday,event_nearby,temperature_c,rain_mm_15min,road_capacity_veh_15min,vehicle_count,...,vehicle_density_per_km,avg_waiting_time_sec,queue_length_veh,incident_flag,prev_count_15min,prev_count_1h,count_same_time_yesterday,count_same_time_last_week,rolling_mean_1h,target_next_count
count,63830.000000,63830.000000,63830.000000,63830.000000,63830.000000,63830.000000,63830.000000,63830.000000,63830.000000,63830.000000,...,63830.000000,63830.000000,63830.000000,63830.000000,63830.000000,63830.000000,63830.000000,63830.000000,63830.000000,63830.000000
mean,11.499499,22.505875,2.970562,0.277393,0.023234,0.003274,17.675656,0.323018,395.020523,134.610575,...,22.246351,21.153608,16.433771,0.023046,134.585101,134.542457,134.266975,134.513552,134.565694,134.623923
std,6.921221,16.771691,1.992865,0.447716,0.150646,0.057128,7.110720,1.045038,93.158648,135.049914,...,40.340031,20.996369,30.304676,0.150049,135.043008,135.041474,134.696453,135.121858,133.091249,135.047644
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,260.000000,1.000000,...,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,5.250000,1.000000
25%,6.000000,15.000000,1.000000,0.000000,0.000000,0.000000,12.300000,0.000000,260.000000,32.000000,...,2.900000,8.600000,1.100000,0.000000,32.000000,32.000000,32.000000,32.000000,32.500000,32.000000
50%,11.000000,15.000000,3.000000,0.000000,0.000000,0.000000,18.500000,0.000000,420.000000,85.000000,...,8.100000,14.200000,4.100000,0.000000,85.000000,85.000000,85.000000,85.000000,86.500000,85.000000
75%,17.000000,45.000000,5.000000,1.000000,0.000000,0.000000,23.100000,0.000000,520.000000,191.000000,...,19.900000,24.300000,14.300000,0.000000,191.000000,190.000000,190.000000,191.000000,190.750000,191.000000
max,23.000000,45.000000,6.000000,1.000000,1.000000,1.000000,31.500000,12.300000,520.000000,546.000000,...,440.900000,118.900000,165.200000,1.000000,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000

In [14]:
data['timestamp'] = pd.to_datetime(data['timestamp'])

In [16]:
data.dtypes

timestamp                    datetime64[us]
intersection_id                         str
hour                                  int64
minute                                int64
day_of_week                           int64
is_weekend                            int64
is_holiday                            int64
event_nearby                          int64
temperature_c                       float64
rain_mm_15min                       float64
road_capacity_veh_15min               int64
vehicle_count                         int64
avg_speed_kmh                       float64
vehicle_density_per_km              float64
avg_waiting_time_sec                float64
queue_length_veh                    float64
incident_flag                         int64
prev_count_15min                    float64
prev_count_1h                       float64
count_same_time_yesterday           float64
count_same_time_last_week           float64
rolling_mean_1h                     float64
target_next_count                   float64
target_congestion                       str
dtype: object

In [19]:
data['incident_flag'].unique()

array([0, 1])

In [20]:
data['target_congestion'].unique()

<StringArray>
['Low', 'Moderate', 'High', 'Severe']
Length: 4, dtype: str

In [21]:
data["numberic_Congestion"] = data["target_congestion"].map({"Low": 0, "Moderate": 1, "High": 2, "Severe": 3})

In [22]:
data.info()

<class 'pandas.DataFrame'>
Index: 63830 entries, 672 to 69118
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   timestamp                  63830 non-null  datetime64[us]
 1   intersection_id            63830 non-null  str
 2   hour                       63830 non-null  int64
 3   minute                     63830 non-null  int64
 4   day_of_week                63830 non-null  int64
 5   is_weekend                 63830 non-null  int64
 6   is_holiday                 63830 non-null  int64
 7   event_nearby               63830 non-null  int64
 8   temperature_c              63830 non-null  float64
 9   rain_mm_15min              63830 non-null  float64
 10  road_capacity_veh_15min    63830 non-null  int64
 11  vehicle_count              63830 non-null  int64
 12  avg_speed_kmh              63830 non-null  float64
 13  vehicle_density_per_km     63830 non-null  float64
 14  avg_waiting_time_sec       63830 non-null  float64
 15  queue_length_veh           63830 non-null  float64
 16  incident_flag              63830 non-null  int64
 17  prev_count_15min           63830 non-null  float64
 18  prev_count_1h              63830 non-null  float64
 19  count_same_time_yesterday  63830 non-null  float64
 20  count_same_time_last_week  63830 non-null  float64
 21  rolling_mean_1h            63830 non-null  float64
 22  target_next_count          63830 non-null  float64
 23  target_congestion          63830 non-null  str
 24  numberic_Congestion        63830 non-null  int64
dtypes: datetime64[us](1), float64(12), int64(10), str(2)
memory usage: 12.7 MB

In [24]:
data.to_csv(r'C:\Users\KIIT\OneDrive\urban_traffic\data\cleaned\re_cleaned.csv')

In [25]:
data1 = pd.read_csv(r'C:\Users\KIIT\OneDrive\urban_traffic\data\cleaned\re_cleaned.csv')

In [28]:
data1.shape

(63830, 26)

In [42]:
data1.iloc[20:50,25]

20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    1
28    1
29    2
30    2
31    3
32    3
33    3
34    3
35    2
36    2
37    2
38    2
39    1
40    1
41    0
42    1
43    0
44    0
45    0
46    1
47    0
48    0
49    0
Name: numberic_Congestion, dtype: int64